name: flutter_template
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  effective_dart: ^1.3.1
  dart_enum_to_string_check: ^0.7.2
  dart_code_metrics: ^3.2.2

flutter:
  uses-material-design: true
